# Generated by Django 2.0 on 2018-03-18 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stays', '0002_stay_validate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stay',
            old_name='validate',
            new_name='is_validate',
        ),
    ]
