# Generated by Django 2.0 on 2018-03-18 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stays', '0003_auto_20180318_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stay',
            old_name='is_validate',
            new_name='is_validated',
        ),
    ]
